---
    - name: upgrade all packages
      yum:
        name: "*"
        state: latest
    - name: Remove docker if installed from CentOS repo
      yum:
        name: 
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest 

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
    
    - name: pip install
      package:
        name: python3-pip
        state: present
    
    - name: Install docker-SDK
      pip:
        name: docker
    
    - name: Add user ec2-user to docker group
      user:
        name: ec2-user
        group: docker
        append: yes
    
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
# tasks file for docker
